- name: Example playbook
  hosts: all
  tasks:

  - name: Debug variables
    include_role:
      name: grog.debug-variable
    vars:
      grog_debug_variable_test: "{{ global_test_variable }}"

  - name: Slurp variables dump file
    slurp:
      src: /tmp/ansible.dump
    register: slurpfile

  - name: Print variables dump file
    debug:
      msg: "{{ slurpfile['content'] | b64decode }}"
